### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  id: TimeSpanSecondsOrInfiniteConverter
  children:
  - System.Configuration.TimeSpanSecondsOrInfiniteConverter.#ctor
  - System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TimeSpanSecondsOrInfiniteConverter
  nameWithType: TimeSpanSecondsOrInfiniteConverter
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  type: Class
  summary: "Konverterer en <xref:System.TimeSpan>uttrykt i sekunder, eller som en standard uendelig gang span.</xref:System.TimeSpan>"
  remarks: "Denne typen som alle de andre konfigurasjon konverteringsprogram typene, konverterer strenger i konfigurasjonsfilen til og fra de forespørselsparameter av sterk type egenskapene.       Spesielt TimeSpanSecondsOrInfiniteConverter konverterer <xref:System.String>sekunder tilordnet et configuration-egenskapen til <xref:System.TimeSpan>sekunder, og omvendt.</xref:System.TimeSpan> </xref:System.String> Hvis konfigurasjonsegenskapen har en <xref:System.String>verdien &quot;uendelig&quot;, konverterer denne verdien til <xref:System.TimeSpan>og omvendt.</xref:System.TimeSpan> </xref:System.String>       Uendelige <xref:System.TimeSpan>verdien som er representert av den <xref:System.TimeSpan.MaxValue>opplistingsverdien.</xref:System.TimeSpan.MaxValue> </xref:System.TimeSpan>"
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: 'public sealed class TimeSpanSecondsOrInfiniteConverter : System.Configuration.TimeSpanSecondsConverter'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  - System.Configuration.TimeSpanSecondsConverter
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  langs:
  - csharp
  name: TimeSpanSecondsOrInfiniteConverter()
  nameWithType: TimeSpanSecondsOrInfiniteConverter.TimeSpanSecondsOrInfiniteConverter()
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.TimeSpanSecondsOrInfiniteConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.TimeSpanSecondsOrInfiniteConverter&quot;> </xref> klasse."
  remarks: "Vanligvis bruker konverteringsprogram typene som er angitt av systemet. Den eneste gangen du må bruke TimeSpanSecondsOrInfiniteConverter konstruktøren er når du oppretter en konverteringstype."
  syntax:
    content: public TimeSpanSecondsOrInfiniteConverter ();
    parameters: []
  overload: System.Configuration.TimeSpanSecondsOrInfiniteConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Konverterer en <xref:System.String>til <xref:System.TimeSpan>.</xref:System.TimeSpan> </xref:System.String>"
  remarks: "Systemet bruker ConvertFrom ved lesing fra en konfigurasjonsfil for å konvertere en <xref:System.String>verdi til <xref:System.TimeSpan>, eller den <xref:System.String>&quot;uendelig&quot; til <xref:System.TimeSpan.MaxValue>.</xref:System.TimeSpan.MaxValue> </xref:System.String> </xref:System.TimeSpan> </xref:System.String>"
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Den <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> objekt som brukes for konverteringer av datatyper."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Den <xref:System.Globalization.CultureInfo>objektet som ble brukt under konvertering.</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "Den <xref:System.String>objekt for å konvertere.</xref:System.String>"
    return:
      type: System.Object
      description: "Den <xref:System.TimeSpan.MaxValue>, hvis den <code> data </code> parameteren er den <xref:System.String>&quot;uendelig&quot;; motsatt fall, av <xref:System.TimeSpan>som representerer den <code> data </code> parameter i sekunder.</xref:System.TimeSpan> </xref:System.String> </xref:System.TimeSpan.MaxValue>"
  overload: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Konverterer en <xref:System.TimeSpan>til a.</xref:System.TimeSpan> <xref:System.String>.</xref:System.String>"
  remarks: "Systemet bruker ConvertTo under skriving til en konfigurasjonsfil for å konvertere en <xref:System.TimeSpan>verdi eller <xref:System.TimeSpan.MaxValue>til en <xref:System.String>.</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.TimeSpan>"
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "Den <xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref> objekt som brukes for konverteringer av datatyper."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "Den <xref:System.Globalization.CultureInfo>objektet som ble brukt under konvertering.</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "Verdien som skal konverteres."
    - id: type
      type: System.Type
      description: "Konverteringstype."
    return:
      type: System.Object
      description: "Den <xref:System.String>&quot;uendelig&quot;, hvis den <code> value </code> parameteren er <xref:System.TimeSpan.MaxValue>; ellers den <xref:System.String>som representerer den <code> value </code> parameter i sekunder.</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.String>"
  overload: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: System.Configuration.TimeSpanSecondsConverter
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.#ctor
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  isExternal: false
  name: TimeSpanSecondsOrInfiniteConverter()
  nameWithType: TimeSpanSecondsOrInfiniteConverter.TimeSpanSecondsOrInfiniteConverter()
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.TimeSpanSecondsOrInfiniteConverter()
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.#ctor*
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  isExternal: false
  name: TimeSpanSecondsOrInfiniteConverter
  nameWithType: TimeSpanSecondsOrInfiniteConverter.TimeSpanSecondsOrInfiniteConverter
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom*
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertFrom
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo*
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertTo
