### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationElementProperty
  id: ConfigurationElementProperty
  children:
  - System.Configuration.ConfigurationElementProperty.#ctor(System.Configuration.ConfigurationValidatorBase)
  - System.Configuration.ConfigurationElementProperty.Validator
  langs:
  - csharp
  name: ConfigurationElementProperty
  nameWithType: ConfigurationElementProperty
  fullName: System.Configuration.ConfigurationElementProperty
  type: Class
  summary: "Angir egenskapen for et konfigurasjonselementet. Denne klassen kan ikke arves."
  remarks: "Denne klassen kan brukes til 책 validere konfigurasjonsegenskaper for elementet. Denne klassen kan ogs책 brukes sammen med <xref:System.Configuration.ConfigurationElement>klasse.</xref:System.Configuration.ConfigurationElement>"
  syntax:
    content: public sealed class ConfigurationElementProperty
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementProperty.#ctor(System.Configuration.ConfigurationValidatorBase)
  id: '#ctor(System.Configuration.ConfigurationValidatorBase)'
  parent: System.Configuration.ConfigurationElementProperty
  langs:
  - csharp
  name: ConfigurationElementProperty(ConfigurationValidatorBase)
  nameWithType: ConfigurationElementProperty.ConfigurationElementProperty(ConfigurationValidatorBase)
  fullName: System.Configuration.ConfigurationElementProperty.ConfigurationElementProperty(ConfigurationValidatorBase)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Configuration.ConfigurationElementProperty&quot;> </xref> klasse, basert p책 den angitte parameter."
  syntax:
    content: public ConfigurationElementProperty (System.Configuration.ConfigurationValidatorBase validator);
    parameters:
    - id: validator
      type: System.Configuration.ConfigurationValidatorBase
      description: "A <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;></xref> object."
  overload: System.Configuration.ConfigurationElementProperty.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>validator</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementProperty.Validator
  id: Validator
  parent: System.Configuration.ConfigurationElementProperty
  langs:
  - csharp
  name: Validator
  nameWithType: ConfigurationElementProperty.Validator
  fullName: System.Configuration.ConfigurationElementProperty.Validator
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Henter en <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> objektet brukes til 책 validere den <xref href=&quot;System.Configuration.ConfigurationElementProperty&quot;> </xref> objektet."
  syntax:
    content: public System.Configuration.ConfigurationValidatorBase Validator { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "A <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;></xref> object."
  overload: System.Configuration.ConfigurationElementProperty.Validator*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationElementProperty.#ctor(System.Configuration.ConfigurationValidatorBase)
  parent: System.Configuration.ConfigurationElementProperty
  isExternal: false
  name: ConfigurationElementProperty(ConfigurationValidatorBase)
  nameWithType: ConfigurationElementProperty.ConfigurationElementProperty(ConfigurationValidatorBase)
  fullName: System.Configuration.ConfigurationElementProperty.ConfigurationElementProperty(ConfigurationValidatorBase)
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.ConfigurationElementProperty.Validator
  parent: System.Configuration.ConfigurationElementProperty
  isExternal: false
  name: Validator
  nameWithType: ConfigurationElementProperty.Validator
  fullName: System.Configuration.ConfigurationElementProperty.Validator
- uid: System.Configuration.ConfigurationElementProperty.#ctor*
  parent: System.Configuration.ConfigurationElementProperty
  isExternal: false
  name: ConfigurationElementProperty
  nameWithType: ConfigurationElementProperty.ConfigurationElementProperty
- uid: System.Configuration.ConfigurationElementProperty.Validator*
  parent: System.Configuration.ConfigurationElementProperty
  isExternal: false
  name: Validator
  nameWithType: ConfigurationElementProperty.Validator
